var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/[...nextauth]/route.js")
R.c("server/chunks/48806_next_7a7e38b6._.js")
R.c("server/chunks/48806_next-auth_08a0c5e4._.js")
R.c("server/chunks/48806_openid-client_2dc09c4d._.js")
R.c("server/chunks/48806_jose_dist_node_cjs_66bddb64._.js")
R.c("server/chunks/[root-of-the-server]__8bb4b4e8._.js")
R.c("server/chunks/[root-of-the-server]__5eb6254c._.js")
R.c("server/chunks/1552c_client__next-internal_server_app_api_auth_[___nextauth]_route_actions_7602af34.js")
R.m("[project]/Desktop/growtools/client/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/Desktop/growtools/client/src/app/api/auth/[...nextauth]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/Desktop/growtools/client/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/Desktop/growtools/client/src/app/api/auth/[...nextauth]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
